# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_app', '0008_auto_20161209_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subreddit',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
